/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PesquisarRouteImport } from './routes/pesquisar'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as GolpesRouteImport } from './routes/golpes'
import { Route as FakeNewsRouteImport } from './routes/fake-news'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RFolderRouteImport } from './routes/r/$folder'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as RFolderRouteRouteImport } from './routes/r/$folder/$route'
import { Route as AuthenticatedPainelNovoRouteImport } from './routes/_authenticated/painel.novo'
import { Route as AuthenticatedPainelEditarIdRouteImport } from './routes/_authenticated/painel.editar.$id'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisarRoute = PesquisarRouteImport.update({
  id: '/pesquisar',
  path: '/pesquisar',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const GolpesRoute = GolpesRouteImport.update({
  id: '/golpes',
  path: '/golpes',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeNewsRoute = FakeNewsRouteImport.update({
  id: '/fake-news',
  path: '/fake-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RFolderRoute = RFolderRouteImport.update({
  id: '/r/$folder',
  path: '/r/$folder',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const RFolderRouteRoute = RFolderRouteRouteImport.update({
  id: '/$route',
  path: '/$route',
  getParentRoute: () => RFolderRoute,
} as any)
const AuthenticatedPainelNovoRoute = AuthenticatedPainelNovoRouteImport.update({
  id: '/painel/novo',
  path: '/painel/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelEditarIdRoute =
  AuthenticatedPainelEditarIdRouteImport.update({
    id: '/painel/editar/$id',
    path: '/painel/editar/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/fake-news': typeof FakeNewsRoute
  '/golpes': typeof GolpesRoute
  '/metodologia': typeof MetodologiaRoute
  '/noticias': typeof NoticiasRoute
  '/pesquisar': typeof PesquisarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/transparencia': typeof TransparenciaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/r/$folder': typeof RFolderRouteWithChildren
  '/painel/novo': typeof AuthenticatedPainelNovoRoute
  '/r/$folder/$route': typeof RFolderRouteRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/painel/editar/$id': typeof AuthenticatedPainelEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/fake-news': typeof FakeNewsRoute
  '/golpes': typeof GolpesRoute
  '/metodologia': typeof MetodologiaRoute
  '/noticias': typeof NoticiasRoute
  '/pesquisar': typeof PesquisarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/transparencia': typeof TransparenciaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/r/$folder': typeof RFolderRouteWithChildren
  '/painel/novo': typeof AuthenticatedPainelNovoRoute
  '/r/$folder/$route': typeof RFolderRouteRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/painel/editar/$id': typeof AuthenticatedPainelEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/fake-news': typeof FakeNewsRoute
  '/golpes': typeof GolpesRoute
  '/metodologia': typeof MetodologiaRoute
  '/noticias': typeof NoticiasRoute
  '/pesquisar': typeof PesquisarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/transparencia': typeof TransparenciaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/r/$folder': typeof RFolderRouteWithChildren
  '/_authenticated/painel/novo': typeof AuthenticatedPainelNovoRoute
  '/r/$folder/$route': typeof RFolderRouteRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/painel/editar/$id': typeof AuthenticatedPainelEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/categorias'
    | '/contato'
    | '/fake-news'
    | '/golpes'
    | '/metodologia'
    | '/noticias'
    | '/pesquisar'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/transparencia'
    | '/categoria/$slug'
    | '/r/$folder'
    | '/painel/novo'
    | '/r/$folder/$route'
    | '/painel/'
    | '/painel/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/categorias'
    | '/contato'
    | '/fake-news'
    | '/golpes'
    | '/metodologia'
    | '/noticias'
    | '/pesquisar'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/transparencia'
    | '/categoria/$slug'
    | '/r/$folder'
    | '/painel/novo'
    | '/r/$folder/$route'
    | '/painel'
    | '/painel/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/categorias'
    | '/contato'
    | '/fake-news'
    | '/golpes'
    | '/metodologia'
    | '/noticias'
    | '/pesquisar'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/transparencia'
    | '/categoria/$slug'
    | '/r/$folder'
    | '/_authenticated/painel/novo'
    | '/r/$folder/$route'
    | '/_authenticated/painel/'
    | '/_authenticated/painel/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  CategoriasRoute: typeof CategoriasRoute
  ContatoRoute: typeof ContatoRoute
  FakeNewsRoute: typeof FakeNewsRoute
  GolpesRoute: typeof GolpesRoute
  MetodologiaRoute: typeof MetodologiaRoute
  NoticiasRoute: typeof NoticiasRoute
  PesquisarRoute: typeof PesquisarRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TransparenciaRoute: typeof TransparenciaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  RFolderRoute: typeof RFolderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisar': {
      id: '/pesquisar'
      path: '/pesquisar'
      fullPath: '/pesquisar'
      preLoaderRoute: typeof PesquisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golpes': {
      id: '/golpes'
      path: '/golpes'
      fullPath: '/golpes'
      preLoaderRoute: typeof GolpesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake-news': {
      id: '/fake-news'
      path: '/fake-news'
      fullPath: '/fake-news'
      preLoaderRoute: typeof FakeNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$folder': {
      id: '/r/$folder'
      path: '/r/$folder'
      fullPath: '/r/$folder'
      preLoaderRoute: typeof RFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$folder/$route': {
      id: '/r/$folder/$route'
      path: '/$route'
      fullPath: '/r/$folder/$route'
      preLoaderRoute: typeof RFolderRouteRouteImport
      parentRoute: typeof RFolderRoute
    }
    '/_authenticated/painel/novo': {
      id: '/_authenticated/painel/novo'
      path: '/painel/novo'
      fullPath: '/painel/novo'
      preLoaderRoute: typeof AuthenticatedPainelNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/editar/$id': {
      id: '/_authenticated/painel/editar/$id'
      path: '/painel/editar/$id'
      fullPath: '/painel/editar/$id'
      preLoaderRoute: typeof AuthenticatedPainelEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelNovoRoute: typeof AuthenticatedPainelNovoRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedPainelEditarIdRoute: typeof AuthenticatedPainelEditarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelNovoRoute: AuthenticatedPainelNovoRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedPainelEditarIdRoute: AuthenticatedPainelEditarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RFolderRouteChildren {
  RFolderRouteRoute: typeof RFolderRouteRoute
}

const RFolderRouteChildren: RFolderRouteChildren = {
  RFolderRouteRoute: RFolderRouteRoute,
}

const RFolderRouteWithChildren =
  RFolderRoute._addFileChildren(RFolderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  CategoriasRoute: CategoriasRoute,
  ContatoRoute: ContatoRoute,
  FakeNewsRoute: FakeNewsRoute,
  GolpesRoute: GolpesRoute,
  MetodologiaRoute: MetodologiaRoute,
  NoticiasRoute: NoticiasRoute,
  PesquisarRoute: PesquisarRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TransparenciaRoute: TransparenciaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  RFolderRoute: RFolderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
